### ISSUE TITLE
Showing the current value of the slider

### ISSUE THREAD

**Issue by Reached** [ElevateDev/meteor-autoform-nouislider#11]
Hi,
Is it possible to show the current value of the slider in the view as shown on the noUiSlider examples?

Thank you

**Comment by superandrew213** [comment]
http://refreshless.com/nouislider/slider-options/#section-tooltips

**Comment by jimmiebtlr** [comment]
Does the section tooltips solve it for you?

**Comment by miri-am** [comment]
Did not work for me. Example would be great.

**Comment by superandrew213** [comment]
If you use this:

```
tooltips: [ false, wNumb({ decimals: 1 }) ]
```

then you need to add wNumb if you haven't already. Otherwise just set it to this:

```
tooltips: true
```

You can also do it without the tooltip and do it manually by using events and helpers. 

Listen when the slider updates in events then store this value in a session variable or a reactive var. Then return it using a helper and call it inside your template just under the noUISlider field.
